apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ${infrastructure_id} 
  name: ${infrastructure_id}-windows-worker-${zone}
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ${infrastructure_id}
      machine.openshift.io/cluster-api-machineset: ${infrastructure_id}-windows-worker-${zone}
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ${infrastructure_id}
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ${infrastructure_id}-windows-worker-${zone}
        machine.openshift.io/os-id: Windows
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          ami:
            id: ${windows_base_ami}
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: ${infrastructure_id}-worker-profile
          instanceType: m5a.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: ${zone}
            region: ${region}
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - ${infrastructure_id}-worker-sg
          subnet:
            filters:
              - name: tag:Name
                values:
                  - ${infrastructure_id}-private-${zone}
          tags:
            - name: kubernetes.io/cluster/${infrastructure_id}
              value: owned
            - name: Contact
              value: ${email}
            - name: DeleteBy
              value: ${delete_by}
            - name: AlwaysUp
              value: ${always_up}
          userDataSecret:
            name: windows-user-data
            namespace: openshift-machine-api