name: force-remove-cluster

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Short name of cluster INCLUDING unquie id (i.e. ocp-test-01-a4j8a)'
        required: true
      aws_region:
        description: 'region in aws'
        required: true
      s3_storage:
        description: 'AWS S3 storage bucket name (i.e. ocp-s3-storage)'
        required: true

jobs:
  force-remove-cluster:
    runs-on: macos-latest
    env:
      temp_dir: "temp-${{ github.run_number }}"
    steps:
      - name: "Checkout ${{ github.ref }}"
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Download OpenShift installer and update permissions
        shell: bash
        run: |
          mkdir -p ./${{ env.lcl_install_dir }}
          echo "Downloading OpenShift Installer..."
          wget -q https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${{ env.ocpVersion }}/openshift-install-mac.tar.gz
          tar -xvzf openshift-install-mac.tar.gz
          echo "Update permissions to executable on the openshift-installer..."
          chmod +x ./openshift-install
          echo "OCP_VERSION=$(./openshift-install version | head -n 1)" >> $GITHUB_ENV

      - name: Create force retire metadata
        shell: bash
        run: |
          mkdir -p ./${{ env.temp_dir }}
          mkdir -p ./${{ env.temp_dir }}/${{ github.event.inputs.clusterName }}
          export ID=${RANDOM:0:10000}
          export aws_region="${{ github.event.inputs.aws_region }}"
          export clusterName="${{ github.event.inputs.clusterName }}"
          envsubst < ./destroy-configs/metadata.json > ./${{ env.temp_dir }}/${{ github.event.inputs.clusterName }}/metadata.json

      - name: Destroy cluster
        shell: bash
        run: |
          ./openshift-install destroy cluster --dir=./${{ env.temp_dir }}/${{ github.event.inputs.clusterName }}

